[[:is_term_resized, [:int, :int], :int],
 [:keybound, [:int, :int], :string],
 [:curses_version, [], :string],
 [:assume_default_colors, [:int, :int], :int],
 [:define_key, [:string, :int], :int],
 [:key_defined, [:string], :int],
 [:keyok, [:int, :int], :int],
 [:resize_term, [:int, :int], :int],
 [:resizeterm, [:int, :int], :int],
 [:use_default_colors, [], :int],
 [:use_extended_names, [:int], :int],
 [:wresize, [:pointer, :int, :int], :int],
 [:addch, [:uint], :int],
 [:addchnstr, [:pointer, :int], :int],
 [:addchstr, [:pointer], :int],
 [:addnstr, [:string, :int], :int],
 [:addstr, [:string], :int],
 [:attroff, [:uint], :int],
 [:attron, [:uint], :int],
 [:attrset, [:uint], :int],
 [:attr_get, [:pointer, :pointer, :pointer], :int],
 [:attr_off, [:uint, :pointer], :int],
 [:attr_on, [:uint, :pointer], :int],
 [:attr_set, [:uint, :short, :pointer], :int],
 [:baudrate, [], :int],
 [:beep, [], :int],
 [:bkgd, [:uint], :int],
 [:bkgdset, [:uint], :void],
 [:border, [:uint, :uint, :uint, :uint, :uint, :uint, :uint, :uint], :int],
 [:box, [:pointer, :uint, :uint], :int],
 [:can_change_color, [], :int],
 [:cbreak, [], :int],
 [:chgat, [:int, :uint, :short, :pointer], :int],
 [:clear, [], :int],
 [:clearok, [:pointer, :int], :int],
 [:clrtobot, [], :int],
 [:clrtoeol, [], :int],
 [:color_content, [:short, :pointer, :pointer, :pointer], :int],
 [:color_set, [:short, :pointer], :int],
 [:COLOR_PAIR, [:int], :int],
 [:copywin,
  [:pointer, :pointer, :int, :int, :int, :int, :int, :int, :int],
  :int],
 [:curs_set, [:int], :int],
 [:def_prog_mode, [], :int],
 [:def_shell_mode, [], :int],
 [:delay_output, [:int], :int],
 [:delch, [], :int],
 [:delscreen, [:pointer], :void],
 [:delwin, [:pointer], :int],
 [:deleteln, [], :int],
 [:derwin, [:pointer, :int, :int, :int, :int], :pointer],
 [:doupdate, [], :int],
 [:dupwin, [:pointer], :pointer],
 [:echo, [], :int],
 [:echochar, [:uint], :int],
 [:erase, [], :int],
 [:endwin, [], :int],
 [:erasechar, [], :char],
 [:filter, [], :void],
 [:flash, [], :int],
 [:flushinp, [], :int],
 [:getbkgd, [:pointer], :uint],
 [:getch, [], :int],
 [:getnstr, [:string, :int], :int],
 [:getstr, [:string], :int],
 [:getwin, [:pointer], :pointer],
 [:halfdelay, [:int], :int],
 [:has_colors, [], :int],
 [:has_ic, [], :int],
 [:has_il, [], :int],
 [:hline, [:uint, :int], :int],
 [:idcok, [:pointer, :int], :void],
 [:idlok, [:pointer, :int], :int],
 [:immedok, [:pointer, :int], :void],
 [:inch, [], :uint],
 [:inchnstr, [:pointer, :int], :int],
 [:inchstr, [:pointer], :int],
 [:initscr, [], :pointer],
 [:init_color, [:short, :short, :short, :short], :int],
 [:init_pair, [:short, :short, :short], :int],
 [:innstr, [:string, :int], :int],
 [:insch, [:uint], :int],
 [:insdelln, [:int], :int],
 [:insertln, [], :int],
 [:insnstr, [:string, :int], :int],
 [:insstr, [:string], :int],
 [:instr, [:string], :int],
 [:intrflush, [:pointer, :int], :int],
 [:isendwin, [], :int],
 [:is_linetouched, [:pointer, :int], :int],
 [:is_wintouched, [:pointer], :int],
 [:keyname, [:int], :string],
 [:keypad, [:pointer, :int], :int],
 [:killchar, [], :char],
 [:leaveok, [:pointer, :int], :int],
 [:longname, [], :string],
 [:meta, [:pointer, :int], :int],
 [:move, [:int, :int], :int],
 [:mvaddch, [:int, :int, :uint], :int],
 [:mvaddchnstr, [:int, :int, :pointer, :int], :int],
 [:mvaddchstr, [:int, :int, :pointer], :int],
 [:mvaddnstr, [:int, :int, :string, :int], :int],
 [:mvaddstr, [:int, :int, :string], :int],
 [:mvchgat, [:int, :int, :int, :uint, :short, :pointer], :int],
 [:mvcur, [:int, :int, :int, :int], :int],
 [:mvdelch, [:int, :int], :int],
 [:mvderwin, [:pointer, :int, :int], :int],
 [:mvgetch, [:int, :int], :int],
 [:mvgetnstr, [:int, :int, :string, :int], :int],
 [:mvgetstr, [:int, :int, :string], :int],
 [:mvhline, [:int, :int, :uint, :int], :int],
 [:mvinch, [:int, :int], :uint],
 [:mvinchnstr, [:int, :int, :pointer, :int], :int],
 [:mvinchstr, [:int, :int, :pointer], :int],
 [:mvinnstr, [:int, :int, :string, :int], :int],
 [:mvinsch, [:int, :int, :uint], :int],
 [:mvinsnstr, [:int, :int, :string, :int], :int],
 [:mvinsstr, [:int, :int, :string], :int],
 [:mvinstr, [:int, :int, :string], :int],
 [:mvvline, [:int, :int, :uint, :int], :int],
 [:mvwaddch, [:pointer, :int, :int, :uint], :int],
 [:mvwaddchnstr, [:pointer, :int, :int, :pointer, :int], :int],
 [:mvwaddchstr, [:pointer, :int, :int, :pointer], :int],
 [:mvwaddnstr, [:pointer, :int, :int, :string, :int], :int],
 [:mvwaddstr, [:pointer, :int, :int, :string], :int],
 [:mvwchgat, [:pointer, :int, :int, :int, :uint, :short, :pointer], :int],
 [:mvwdelch, [:pointer, :int, :int], :int],
 [:mvwgetch, [:pointer, :int, :int], :int],
 [:mvwgetnstr, [:pointer, :int, :int, :string, :int], :int],
 [:mvwgetstr, [:pointer, :int, :int, :string], :int],
 [:mvwhline, [:pointer, :int, :int, :uint, :int], :int],
 [:mvwin, [:pointer, :int, :int], :int],
 [:mvwinch, [:pointer, :int, :int], :uint],
 [:mvwinchnstr, [:pointer, :int, :int, :pointer, :int], :int],
 [:mvwinchstr, [:pointer, :int, :int, :pointer], :int],
 [:mvwinnstr, [:pointer, :int, :int, :string, :int], :int],
 [:mvwinsch, [:pointer, :int, :int, :uint], :int],
 [:mvwinsnstr, [:pointer, :int, :int, :string, :int], :int],
 [:mvwinsstr, [:pointer, :int, :int, :string], :int],
 [:mvwinstr, [:pointer, :int, :int, :string], :int],
 [:mvwvline, [:pointer, :int, :int, :uint, :int], :int],
 [:napms, [:int], :int],
 [:newpad, [:int, :int], :pointer],
 [:newterm, [:string, :pointer, :pointer], :pointer],
 [:newwin, [:int, :int, :int, :int], :pointer],
 [:nl, [], :int],
 [:nocbreak, [], :int],
 [:nodelay, [:pointer, :int], :int],
 [:noecho, [], :int],
 [:nonl, [], :int],
 [:noqiflush, [], :void],
 [:noraw, [], :int],
 [:notimeout, [:pointer, :int], :int],
 [:overlay, [:pointer, :pointer], :int],
 [:overwrite, [:pointer, :pointer], :int],
 [:pair_content, [:short, :pointer, :pointer], :int],
 [:PAIR_NUMBER, [:int], :int],
 [:pechochar, [:pointer, :uint], :int],
 [:pnoutrefresh, [:pointer, :int, :int, :int, :int, :int, :int], :int],
 [:prefresh, [:pointer, :int, :int, :int, :int, :int, :int], :int],
 [:putp, [:string], :int],
 [:putwin, [:pointer, :pointer], :int],
 [:qiflush, [], :void],
 [:raw, [], :int],
 [:redrawwin, [:pointer], :int],
 [:refresh, [], :int],
 [:resetty, [], :int],
 [:reset_prog_mode, [], :int],
 [:reset_shell_mode, [], :int],
 [:ripoffline, [:int, :pointer], :int],
 [:savetty, [], :int],
 [:scr_dump, [:string], :int],
 [:scr_init, [:string], :int],
 [:scrl, [:int], :int],
 [:scroll, [:pointer], :int],
 [:scrollok, [:pointer, :int], :int],
 [:scr_restore, [:string], :int],
 [:scr_set, [:string], :int],
 [:setscrreg, [:int, :int], :int],
 [:set_term, [:pointer], :pointer],
 [:slk_attroff, [:uint], :int],
 [:slk_attr_off, [:uint, :pointer], :int],
 [:slk_attron, [:uint], :int],
 [:slk_attr_on, [:uint, :pointer], :int],
 [:slk_attrset, [:uint], :int],
 [:slk_attr, [], :uint],
 [:slk_attr_set, [:uint, :short, :pointer], :int],
 [:slk_clear, [], :int],
 [:slk_color, [:short], :int],
 [:slk_init, [:int], :int],
 [:slk_label, [:int], :string],
 [:slk_noutrefresh, [], :int],
 [:slk_refresh, [], :int],
 [:slk_restore, [], :int],
 [:slk_set, [:int, :string, :int], :int],
 [:slk_touch, [], :int],
 [:standout, [], :int],
 [:standend, [], :int],
 [:start_color, [], :int],
 [:subpad, [:pointer, :int, :int, :int, :int], :pointer],
 [:subwin, [:pointer, :int, :int, :int, :int], :pointer],
 [:syncok, [:pointer, :int], :int],
 [:termattrs, [], :uint],
 [:termname, [], :string],
 [:tigetflag, [:string], :int],
 [:tigetnum, [:string], :int],
 [:tigetstr, [:string], :string],
 [:timeout, [:int], :void],
 [:touchline, [:pointer, :int, :int], :int],
 [:touchwin, [:pointer], :int],
 [:typeahead, [:int], :int],
 [:ungetch, [:int], :int],
 [:untouchwin, [:pointer], :int],
 [:use_env, [:int], :void],
 [:vidattr, [:uint], :int],
 [:vidputs, [:uint, :pointer], :int],
 [:vline, [:uint, :int], :int],
 [:waddch, [:pointer, :uint], :int],
 [:waddchnstr, [:pointer, :pointer, :int], :int],
 [:waddchstr, [:pointer, :pointer], :int],
 [:waddnstr, [:pointer, :string, :int], :int],
 [:waddstr, [:pointer, :string], :int],
 [:wattron, [:pointer, :int], :int],
 [:wattroff, [:pointer, :int], :int],
 [:wattrset, [:pointer, :int], :int],
 [:wattr_get, [:pointer, :pointer, :pointer, :pointer], :int],
 [:wattr_on, [:pointer, :uint, :pointer], :int],
 [:wattr_off, [:pointer, :uint, :pointer], :int],
 [:wattr_set, [:pointer, :uint, :short, :pointer], :int],
 [:wbkgd, [:pointer, :uint], :int],
 [:wbkgdset, [:pointer, :uint], :void],
 [:wborder,
  [:pointer, :uint, :uint, :uint, :uint, :uint, :uint, :uint, :uint],
  :int],
 [:wchgat, [:pointer, :int, :uint, :short, :pointer], :int],
 [:wclear, [:pointer], :int],
 [:wclrtobot, [:pointer], :int],
 [:wclrtoeol, [:pointer], :int],
 [:wcolor_set, [:pointer, :short, :pointer], :int],
 [:wcursyncup, [:pointer], :void],
 [:wdelch, [:pointer], :int],
 [:wdeleteln, [:pointer], :int],
 [:wechochar, [:pointer, :uint], :int],
 [:werase, [:pointer], :int],
 [:wgetch, [:pointer], :int],
 [:wgetnstr, [:pointer, :string, :int], :int],
 [:wgetstr, [:pointer, :string], :int],
 [:whline, [:pointer, :uint, :int], :int],
 [:winch, [:pointer], :uint],
 [:winchnstr, [:pointer, :pointer, :int], :int],
 [:winchstr, [:pointer, :pointer], :int],
 [:winnstr, [:pointer, :string, :int], :int],
 [:winsch, [:pointer, :uint], :int],
 [:winsdelln, [:pointer, :int], :int],
 [:winsertln, [:pointer], :int],
 [:winsnstr, [:pointer, :string, :int], :int],
 [:winsstr, [:pointer, :string], :int],
 [:winstr, [:pointer, :string], :int],
 [:wmove, [:pointer, :int, :int], :int],
 [:wnoutrefresh, [:pointer], :int],
 [:wredrawln, [:pointer, :int, :int], :int],
 [:wrefresh, [:pointer], :int],
 [:wscrl, [:pointer, :int], :int],
 [:wsetscrreg, [:pointer, :int, :int], :int],
 [:wstandout, [:pointer], :int],
 [:wstandend, [:pointer], :int],
 [:wsyncdown, [:pointer], :void],
 [:wsyncup, [:pointer], :void],
 [:wtimeout, [:pointer, :int], :void],
 [:wtouchln, [:pointer, :int, :int, :int], :int],
 [:wvline, [:pointer, :uint, :int], :int],
 [:add_wch, [:pointer], :int],
 [:add_wchnstr, [:pointer, :int], :int],
 [:add_wchstr, [:pointer], :int],
 [:bkgrnd, [:pointer], :int],
 [:bkgrndset, [:pointer], :void],
 [:border_set,
  [:pointer,
   :pointer,
   :pointer,
   :pointer,
   :pointer,
   :pointer,
   :pointer,
   :pointer],
  :int],
 [:box_set, [:pointer, :pointer, :pointer], :int],
 [:echo_wchar, [:pointer], :int],
 [:getbkgrnd, [:pointer], :int],
 [:hline_set, [:pointer, :int], :int],
 [:in_wch, [:pointer], :int],
 [:in_wchnstr, [:pointer, :int], :int],
 [:in_wchstr, [:pointer], :int],
 [:ins_wch, [:pointer], :int],
 [:mvadd_wch, [:int, :int, :pointer], :int],
 [:mvadd_wchnstr, [:int, :int, :pointer, :int], :int],
 [:mvadd_wchstr, [:int, :int, :pointer], :int],
 [:mvhline_set, [:int, :int, :pointer, :int], :int],
 [:mvin_wch, [:int, :int, :pointer], :int],
 [:mvin_wchnstr, [:int, :int, :pointer, :int], :int],
 [:mvin_wchstr, [:int, :int, :pointer], :int],
 [:mvins_wch, [:int, :int, :pointer], :int],
 [:mvvline_set, [:int, :int, :pointer, :int], :int],
 [:mvwadd_wch, [:pointer, :int, :int, :pointer], :int],
 [:mvwadd_wchnstr, [:pointer, :int, :int, :pointer, :int], :int],
 [:mvwadd_wchstr, [:pointer, :int, :int, :pointer], :int],
 [:mvwhline_set, [:pointer, :int, :int, :pointer, :int], :int],
 [:mvwin_wch, [:pointer, :int, :int, :pointer], :int],
 [:mvwin_wchnstr, [:pointer, :int, :int, :pointer, :int], :int],
 [:mvwin_wchstr, [:pointer, :int, :int, :pointer], :int],
 [:mvwins_wch, [:pointer, :int, :int, :pointer], :int],
 [:mvwvline_set, [:pointer, :int, :int, :pointer, :int], :int],
 [:pecho_wchar, [:pointer, :pointer], :int],
 [:term_attrs, [], :uint],
 [:vid_attr, [:uint, :short, :pointer], :int],
 [:vid_puts, [:uint, :short, :pointer, :pointer], :int],
 [:vline_set, [:pointer, :int], :int],
 [:wadd_wch, [:pointer, :pointer], :int],
 [:wadd_wchnstr, [:pointer, :pointer, :int], :int],
 [:wadd_wchstr, [:pointer, :pointer], :int],
 [:wbkgrnd, [:pointer, :pointer], :int],
 [:wbkgrndset, [:pointer, :pointer], :void],
 [:wborder_set,
  [:pointer,
   :pointer,
   :pointer,
   :pointer,
   :pointer,
   :pointer,
   :pointer,
   :pointer,
   :pointer],
  :int],
 [:wecho_wchar, [:pointer, :pointer], :int],
 [:wgetbkgrnd, [:pointer, :pointer], :int],
 [:whline_set, [:pointer, :pointer, :int], :int],
 [:win_wch, [:pointer, :pointer], :int],
 [:win_wchnstr, [:pointer, :pointer, :int], :int],
 [:win_wchstr, [:pointer, :pointer], :int],
 [:wins_wch, [:pointer, :pointer], :int],
 [:wvline_set, [:pointer, :pointer, :int], :int],
 [:getmouse, [:pointer], :int],
 [:ungetmouse, [:pointer], :int],
 [:mousemask, [:uint, :pointer], :uint],
 [:wenclose, [:pointer, :int, :int], :int],
 [:mouseinterval, [:int], :int],
 [:mouse_trafo, [:pointer, :pointer, :int], :int],
 [:mcprint, [:string, :int], :int],
 [:has_key, [:int], :int],
 [:_tracedump, [:string, :pointer], :void],
 [:_traceattr, [:uint], :string],
 [:_traceattr2, [:int, :uint], :string],
 [:_nc_tracebits, [], :string],
 [:_tracechar, [:int], :string],
 [:_tracechtype, [:uint], :string],
 [:_tracechtype2, [:int, :uint], :string],
 [:_tracecchar_t, [:pointer], :string],
 [:_tracecchar_t2, [:int, :pointer], :string],
 [:_tracemouse, [:pointer], :string],
 [:trace, [:uint], :void],
 [:_nc_visbuf, [:string], :string]]
# 339
# 62
